---
dept_vlan: 40
dept_vlan_name: VLAN_DIS

uplink_interface:
  name: GigabitEthernet0/0
  description: "Trunk uplink to SW-CORE (server farm access)"

access_interfaces:
  - name: GigabitEthernet0/1
    description: "VPC-DIS-1 (server)"
  - name: GigabitEthernet0/2
    description: "VPC-DIS-2 (server)"
